[package]
name = "canister-rs"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.150", features = ["derive"] }
tokio = { version = "1.23.0", features = ["full"] }
